### ISSUE TITLE
What is purpose of this plugin?

### ISSUE THREAD

**Issue by Jeremi360** [thiagola92/autocomplete-unity#2]
Sorry, but I don't understand why your plugin exist - for all C# related projects [OmniSharp](https://atom.io/packages/omnisharp-atom) plugin should be enough.

**Comment by thiagola92** [comment]
I ain't gonna lie, i have no idea how OmniSharp work, how to make it work with Unity3D and it was giving me headache to make it work with anything.  
This package is not even close as useful as OmniSharp, but i wanted something simply to help me a little with the code in Unity3D.  

In others words, this package is probably useless. 😢

**Comment by Jeremi360** [comment]
Sorry, for reality, OmniSharp is buggy, but atom it self form have bulid in c# plugin, but must install atom-ide to get this to work.
